import { LanguageOption } from '../types';

export const LANGUAGES: LanguageOption[] = [
  { code: 'English', name: 'English', nativeName: 'English', flag: '🇺🇸', popular: true },
  { code: 'Spanish', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸', popular: true },
  { code: 'French', name: 'French', nativeName: 'Français', flag: '🇫🇷', popular: true },
  { code: 'German', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪', popular: true },
  { code: 'Chinese (Simplified)', name: 'Chinese (Simplified)', nativeName: '简体中文', flag: '🇨🇳', popular: true },
  { code: 'Japanese', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵', popular: true },
  { code: 'Hindi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳', popular: true },
  { code: 'Arabic', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦', popular: true },
  { code: 'Portuguese', name: 'Portuguese', nativeName: 'Português', flag: '🇵🇹', popular: true },
  { code: 'Russian', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺', popular: true },
  { code: 'Italian', name: 'Italian', nativeName: 'Italiano', flag: '🇮🇹', popular: true },
  { code: 'Korean', name: 'Korean', nativeName: '한국어', flag: '🇰🇷', popular: true },
  { code: 'Dutch', name: 'Dutch', nativeName: 'Nederlands', flag: '🇳🇱' },
  { code: 'Polish', name: 'Polish', nativeName: 'Polski', flag: '🇵🇱' },
  { code: 'Turkish', name: 'Turkish', nativeName: 'Türkçe', flag: '🇹🇷' },
  { code: 'Vietnamese', name: 'Vietnamese', nativeName: 'Tiếng Việt', flag: '🇻🇳' },
  { code: 'Thai', name: 'Thai', nativeName: 'ไทย', flag: '🇹🇭' },
  { code: 'Indonesian', name: 'Indonesian', nativeName: 'Bahasa Indonesia', flag: '🇮🇩' },
  { code: 'Bengali', name: 'Bengali', nativeName: 'বাংলা', flag: '🇧🇩' },
  { code: 'Swedish', name: 'Swedish', nativeName: 'Svenska', flag: '🇸🇪' },
  { code: 'Ukrainian', name: 'Ukrainian', nativeName: 'Українська', flag: '🇺🇦' },
  { code: 'Hebrew', name: 'Hebrew', nativeName: 'עברית', flag: '🇮🇱' },
  { code: 'Greek', name: 'Greek', nativeName: 'Ελληνικά', flag: '🇬🇷' },
  { code: 'Czech', name: 'Czech', nativeName: 'Čeština', flag: '🇨🇿' },
  { code: 'Romanian', name: 'Romanian', nativeName: 'Română', flag: '🇷🇴' },
  { code: 'Hungarian', name: 'Hungarian', nativeName: 'Magyar', flag: '🇭🇺' },
  { code: 'Danish', name: 'Danish', nativeName: 'Dansk', flag: '🇩🇰' },
  { code: 'Finnish', name: 'Finnish', nativeName: 'Suomi', flag: '🇫🇮' },
  { code: 'Norwegian', name: 'Norwegian', nativeName: 'Norsk', flag: '🇳🇴' },
  { code: 'Malay', name: 'Malay', nativeName: 'Bahasa Melayu', flag: '🇲🇾' },
  { code: 'Tagalog (Filipino)', name: 'Tagalog (Filipino)', nativeName: 'Tagalog', flag: '🇵🇭' },
  { code: 'Swahili', name: 'Swahili', nativeName: 'Kiswahili', flag: '🇰🇪' },
  { code: 'Urdu', name: 'Urdu', nativeName: 'اردو', flag: '🇵🇰' },
  { code: 'Persian', name: 'Persian', nativeName: 'فارسی', flag: '🇮🇷' },
  { code: 'Tamil', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳' },
  { code: 'Telugu', name: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳' },
  { code: 'Marathi', name: 'Marathi', nativeName: 'मराठी', flag: '🇮🇳' },
  { code: 'Gujarati', name: 'Gujarati', nativeName: 'ગુજરાતી', flag: '🇮🇳' },
  { code: 'Catalan', name: 'Catalan', nativeName: 'Català', flag: '🇪🇸' },
  { code: 'Serbian', name: 'Serbian', nativeName: 'Српски', flag: '🇷🇸' },
  { code: 'Slovak', name: 'Slovak', nativeName: 'Slovenčina', flag: '🇸🇰' },
  { code: 'Croatian', name: 'Croatian', nativeName: 'Hrvatski', flag: '🇭🇷' }
];
